### PR TITLE
Add CUDA GPU JIT compilation to `faddeeva()`

### PR DESCRIPTION
**Pull request by smokestacklightnin**
### :pencil: Description

**Type:**  :rocket: `feature`

This pull request implements CUDA JITting for Faddeeva. The non-CUDA version of Faddeeva is also refactored. 

The associated tests are included.

This pull request should be merged (hopefully immediately) ***after*** pull request #110 

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request

### CODE REVIEW

**Review by smokestacklightnin — COMMENTED** [review]
The "weird" reimplementation for `_faddeeva()` is such for optimization reasons as discussed [here](https://pythonspeed.com/articles/speeding-up-numba/).

The advantage is that it moves the conditional to decide *what* gets written to the variable `w` rather than *whether* a variable gets written to `w`. This distinction makes it easier for the compiler to optimize our code, according to the article.

**Comment by andrewfullard** [comment]
Could you rebase this PR so it is easier to review?

**Comment by smokestacklightnin** [comment]
> Could you rebase this PR so it is easier to review?

Done

**Review by andrewfullard — APPROVED** [review]

**Review by smithis7 — APPROVED** [review]

**Review by vamads — COMMENTED** [review]
Looks good to me!

**Pull request merged**
